### ISSUE TITLE
This is not recommended 

### ISSUE THREAD

**Issue by alexmanase** [gaby3912/Project1#4]
https://github.com/gaby3912/Project1/blob/6e8a8ab3daf1ea40411962ae814e07f71a6c86a3/css4.css#L1

When you want general rules for all properties it's better to use something like this:

```css
body, html {
  font-famility: sans-serif;
}
```
